default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: devlogger_development

test:
  <<: *default
  database: devlogger_test

production:
  <<: *default
  database: devlogger_production
  username: devlogger
  password: <%= ENV["DEVLOGGER_DATABASE_PASSWORD"] %>
